// <auto-generated />
namespace AdvFeatures.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mot : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mot));
        
        string IMigrationMetadata.Id
        {
            get { return "202012270407080_mot"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
